// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoApp.Data;

#nullable disable

namespace ToDoApp.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20221125191525_DateToTimestamp")]
    partial class DateToTimestamp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToDoApp.Entities.ToDoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedTimestamp")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpiryTimestamp")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ToDoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTimestamp = 1669403725,
                            Description = "This is Task 1.",
                            ExpiryTimestamp = 1669104000,
                            Name = "Task 1",
                            Place = "Dhaka"
                        },
                        new
                        {
                            Id = 2,
                            CreatedTimestamp = 1669403725,
                            Description = "This is Task 2.",
                            ExpiryTimestamp = 1669125600,
                            Name = "Task 2",
                            Place = "Dhaka"
                        },
                        new
                        {
                            Id = 3,
                            CreatedTimestamp = 1669403725,
                            Description = "This is Task 2.",
                            ExpiryTimestamp = 1669071600,
                            Name = "Task 3",
                            Place = "Khulna"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
